#!/bin/bash
#SBATCH -J PinOnly
#SBATCH -o logfile 
#SBATCH -e errfile
#SBATCH -p h100
#SBATCH -N 4
#SBATCH -n 16
#SBATCH -t 01:00:00

export CUDA_HOME=/usr/local/cuda-12.8
export PATH="$CUDA_HOME/bin:$PATH"
export LD_LIBRARY_PATH="$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}"

# --- OCCA/NEKRS GPU settings ---
export OCCA_CUDA_COMPILER="$CUDA_HOME/bin/nvcc"

# Quick sanity check
echo "CUDA_HOME=$CUDA_HOME"
which nvcc && nvcc --version

mpirun -n 16 nekrs --setup flat_plate.par --backend CUDA