#!/bin/bash
#SBATCH -J MPCbase
#SBATCH -o logfile 
#SBATCH -e errfile
#SBATCH -p gh
#SBATCH -N 24
#SBATCH -n 24
#SBATCH --ntasks-per-node 1
#SBATCH -t 24:00:00

module load gcc/14.2.0
module load cuda/12.8
module load cmake/3.31.5
module load python3
module list

#rm -rf .cache
./config.sh

#ibrun nekrs --setup NACA.par
