#!/bin/bash
#SBATCH -J tripR400
#SBATCH -o logfile 
#SBATCH -e errfile
#SBATCH -p gh
#SBATCH -N 16
#SBATCH -n 16
#SBATCH --ntasks-per-node 1
#SBATCH -t 12:00:00

module load gcc/13.2.0
module load cuda/12.8
module load cmake/3.31.5
module list

#rm -rf .cache
./config.sh

#ibrun nekrs --setup NACA.par
